spring:
  datasource:
      url: jdbc:mysql://localhost:3306/dcv
      driverClassName: com.mysql.cj.jdbc.Driver
      username: dcv_user
      password: dcv_password
      hikari:
        initializationFailTimeout: -1  # Set to -1 to disable fail-fast on startup

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update